
// Auto-generated by AutoPilot on 30-07-2023 at 18:07:08

const express = require('express');
const router = express.Router();

// Generate random number between 1 and 10
router.get('/test', (req, res) => {
    let randNum = Math.floor(Math.random() * 10) + 1;
    res.status(200).json({ randomNumber: randNum });
});

// Export router
module.exports = router;